### ISSUE TITLE
Update rofi

### ISSUE THREAD

**Issue by abeluck** [fepitre/qubes-rofi#2]
the latest version of rofi is 1.6.1 (https://github.com/davatorium/rofi/releases/tag/1.6.1)

Any chance we could get this package updated (and released to qubes-contrib?)

**Comment by fepitre** [comment]
Yes I can update it.

**Comment by fepitre** [comment]
Updated to 1.6.0 like Fedora 32+. The package is in R4.0 `current-testing`. For further request, please use `qubes-issues` directly please.
