### ISSUE TITLE
Unknown repo

### ISSUE THREAD

**Issue by Err0r-C0de** [fepitre/qubes-rofi#3]
I followed the steps in https://github.com/fepitre/qubes-rofi/issues/1/#issuecomment-667303259 but it says:
Unable to detect release version (use  '--releasever' to specify release version)
Error: Unknown repo:  'qubes-repo-contrib'
Fetching updates failed with code 1

**Comment by fepitre** [comment]
As stated in #1, this is part of Qubes OS. Please use the mailing list or forum (https://forum.qubes-os.org/) for such request. Thank you.

Please give your Qubes OS version, where you are trying to install the package (dom0...) etc.

**Comment by Err0r-C0de** [comment]
ok thx.
